from problems import generate_data